package ec.gob.ambiente.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2022-02-11T19:49:26.596-05:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebService(targetNamespace = "http://client.ambiente.gob.ec/", name = "SuiaServices")
@XmlSeeAlso({ec.gob.registrocivil.consultanombre.ObjectFactory.class, ec.gob.registrocivil.consultacedula.ObjectFactory.class, ec.gob.turismo.ws.catastro.ObjectFactory.class, ec.gob.arcom.dm.ws.ObjectFactory.class, _154._1._180._10._8080.consultatitulossenescytwsv3.servicioconsultatitulo.ObjectFactory.class, ant.ObjectFactory.class, ObjectFactory.class, ec.gob.registrocivil.ObjectFactory.class, ec.gov.sri.wsconsultacontribuyente.ObjectFactory.class})
public interface SuiaServices {

    @WebMethod
    @RequestWrapper(localName = "getConsultaGuiasPorCedula", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetConsultaGuiasPorCedula")
    @ResponseWrapper(localName = "getConsultaGuiasPorCedulaResponse", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetConsultaGuiasPorCedulaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.gob.turismo.ws.catastro.Respuesta getConsultaGuiasPorCedula(
        @WebParam(name = "Cedula", targetNamespace = "")
        java.lang.String cedula
    );

    @WebMethod
    @RequestWrapper(localName = "getCedula", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetCedula")
    @ResponseWrapper(localName = "getCedulaResponse", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetCedulaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.gob.registrocivil.consultacedula.Cedula getCedula(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "")
        java.lang.String pass,
        @WebParam(name = "cedulaNumber", targetNamespace = "")
        java.lang.String cedulaNumber
    );

    @WebMethod
    @RequestWrapper(localName = "getTitulo", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetTitulo")
    @ResponseWrapper(localName = "getTituloResponse", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetTituloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public _154._1._180._10._8080.consultatitulossenescytwsv3.servicioconsultatitulo.GraduadoReporteDTO getTitulo(
        @WebParam(name = "Cedula", targetNamespace = "")
        java.lang.String cedula
    );

    @WebMethod
    @RequestWrapper(localName = "getLicencia", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetLicencia")
    @ResponseWrapper(localName = "getLicenciaResponse", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetLicenciaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ant.DatosLicencia getLicencia(
        @WebParam(name = "Identifica", targetNamespace = "")
        java.lang.String identifica,
        @WebParam(name = "Canal", targetNamespace = "")
        java.lang.String canal,
        @WebParam(name = "Usuario", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod
    @RequestWrapper(localName = "getNameOld", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetNameOld")
    @ResponseWrapper(localName = "getNameOldResponse", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetNameOldResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.gob.registrocivil.consultanombre.Ciudadanos getNameOld(
        @WebParam(name = "apellido1", targetNamespace = "")
        java.lang.String apellido1,
        @WebParam(name = "apellido2", targetNamespace = "")
        java.lang.String apellido2,
        @WebParam(name = "nombre1", targetNamespace = "")
        java.lang.String nombre1,
        @WebParam(name = "nombre2", targetNamespace = "")
        java.lang.String nombre2,
        @WebParam(name = "edadInicio", targetNamespace = "")
        java.lang.Integer edadInicio,
        @WebParam(name = "edadFinal", targetNamespace = "")
        java.lang.Integer edadFinal,
        @WebParam(name = "genero", targetNamespace = "")
        java.lang.Integer genero
    );

    @WebMethod
    @RequestWrapper(localName = "getCedulaOld", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetCedulaOld")
    @ResponseWrapper(localName = "getCedulaOldResponse", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetCedulaOldResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.gob.registrocivil.consultacedula.Cedula getCedulaOld(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "")
        java.lang.String pass,
        @WebParam(name = "cedulaNumber", targetNamespace = "")
        java.lang.String cedulaNumber
    );

    @WebMethod
    @RequestWrapper(localName = "getMatricula", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetMatricula")
    @ResponseWrapper(localName = "getMatriculaResponse", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetMatriculaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ant.DatosMatricula getMatricula(
        @WebParam(name = "Placa", targetNamespace = "")
        java.lang.String placa,
        @WebParam(name = "Canal", targetNamespace = "")
        java.lang.String canal,
        @WebParam(name = "Usuario", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod
    @RequestWrapper(localName = "getRuc", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetRuc")
    @ResponseWrapper(localName = "getRucResponse", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetRucResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.gov.sri.wsconsultacontribuyente.ContribuyenteCompleto getRuc(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "")
        java.lang.String pass,
        @WebParam(name = "rucNumber", targetNamespace = "")
        java.lang.String rucNumber
    );

    @WebMethod
    @RequestWrapper(localName = "getName", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.gob.registrocivil.Ciudadanos getName(
        @WebParam(name = "apellido1", targetNamespace = "")
        java.lang.String apellido1,
        @WebParam(name = "apellido2", targetNamespace = "")
        java.lang.String apellido2,
        @WebParam(name = "nombre1", targetNamespace = "")
        java.lang.String nombre1,
        @WebParam(name = "nombre2", targetNamespace = "")
        java.lang.String nombre2,
        @WebParam(name = "edadInicio", targetNamespace = "")
        java.lang.String edadInicio,
        @WebParam(name = "edadFinal", targetNamespace = "")
        java.lang.String edadFinal,
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "")
        java.lang.String pass,
        @WebParam(name = "genero", targetNamespace = "")
        java.lang.String genero
    );

    @WebMethod
    @RequestWrapper(localName = "getConsultarCatastral", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetConsultarCatastral")
    @ResponseWrapper(localName = "getConsultarCatastralResponse", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetConsultarCatastralResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.gob.arcom.dm.ws.DerechoMineroMAEDTO getConsultarCatastral(
        @WebParam(name = "codigoCatastral", targetNamespace = "")
        java.lang.String codigoCatastral
    );

    @WebMethod
    @RequestWrapper(localName = "getConsultaGuiasPorFecha", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetConsultaGuiasPorFecha")
    @ResponseWrapper(localName = "getConsultaGuiasPorFechaResponse", targetNamespace = "http://client.ambiente.gob.ec/", className = "ec.gob.ambiente.client.GetConsultaGuiasPorFechaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.gob.turismo.ws.catastro.Respuesta getConsultaGuiasPorFecha(
        @WebParam(name = "Cedula", targetNamespace = "")
        java.lang.String cedula,
        @WebParam(name = "FechaDesde", targetNamespace = "")
        java.lang.String fechaDesde,
        @WebParam(name = "FechaHasta", targetNamespace = "")
        java.lang.String fechaHasta
    );
}
