package ec.gob.ambiente.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2022-02-11T19:49:26.619-05:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebServiceClient(name = "SuiaServices", 
                  wsdlLocation = "http://bpms.ambiente.gob.ec:8099/suiawebservices/SuiaServices?wsdl",
                  targetNamespace = "http://client.ambiente.gob.ec/") 
public class SuiaServices_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://client.ambiente.gob.ec/", "SuiaServices");
    public final static QName SuiaServicesPort = new QName("http://client.ambiente.gob.ec/", "SuiaServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://bpms.ambiente.gob.ec:8099/suiawebservices/SuiaServices?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SuiaServices_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://bpms.ambiente.gob.ec:8099/suiawebservices/SuiaServices?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SuiaServices_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SuiaServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SuiaServices_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns SuiaServices
     */
    @WebEndpoint(name = "SuiaServicesPort")
    public SuiaServices getSuiaServicesPort() {
        return super.getPort(SuiaServicesPort, SuiaServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SuiaServices
     */
    @WebEndpoint(name = "SuiaServicesPort")
    public SuiaServices getSuiaServicesPort(WebServiceFeature... features) {
        return super.getPort(SuiaServicesPort, SuiaServices.class, features);
    }

}
